plugin registration
zurichat/zc_plugin_company_sales_prospect pull request #189
Opened 2021-09-02 23:08 UTC by azeezsodiqkayode

2021-09-02 23:10 UTC, azeezsodiqkayode commented
#65

2021-09-03 07:28 UTC, sparkle666 approved these changes
Yo...

2021-09-03 07:29 UTC, sparkle666 requested changes
Conflict

2021-09-03 09:14 UTC, sparkle666 approved these changes
Looks good to me

2021-09-03 09:15 UTC, merged